# Generated by Django 5.1.5 on 2025-01-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_userprofile_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prise',
            new_name='price',
        ),
    ]
