# Generated by Django 5.1.5 on 2025-01-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_rename_prise_course_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_uti',
            new_name='certificate_url',
        ),
    ]
